create database sales ;
use sales;

select * from [dbo].[customer];
select * from [dbo].[order_items];
select * from [dbo].[orders];
select * from [dbo].[products];


----coustomer analysis Top 5 Customers by Spending ----
SELECT TOP 5 c.name, SUM(p.price * oi.quantity) AS total_spent
FROM [dbo].[customer] c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY c.name
ORDER BY total_spent DESC;

----city has the most customers---
select city,count(*) as total_customer
from [dbo].[customer]  
group by city
order by total_customer desc;

----coustomers with multiple orders --
SELECT c.name, COUNT(o.order_id) AS total_orders
FROM customer c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING COUNT(o.order_id) > 1;


---insights what I find:
---High-value customers
---Repeat customers
---Location-based trends


---------PRODUCT ANALYSIS---------
-------best-selling product (by quantity)--
select p.product_name,sum(o.quantity) as total 
from [dbo].[products]p 
join [dbo].[order_items]o 
on p.product_id = o.product_id
group by product_name
order by total desc;

-------highest revenue generated by product ----
select p.product_name,
sum(p.price) as total_Price,sum(o.quantity) as total_reveneu
from [dbo].[products]p join [dbo].[order_items]o 
on p.product_id = o.product_id 
group by p.product_name,p.price
order by total_Price desc ;


SELECT TOP 1 
    p.product_name,
    SUM(p.price * o.quantity) AS total_revenue
FROM products p
JOIN order_items o 
    ON p.product_id = o.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

SELECT 
    p.product_name,
    SUM(o.quantity) AS total_quantity,
    SUM(p.price * o.quantity) AS total_revenue
FROM [dbo].[products] p
JOIN [dbo].[order_items] o 
    ON p.product_id = o.product_id 
GROUP BY p.product_name
ORDER BY total_revenue DESC;



----------most popular category--------
select top 3 p.category ,sum(o.quantity ) as total
from [dbo].[products]p join [dbo].[order_items]o 
on p.product_id = o.product_id
group by p.category 
order by  total desc;



----------SALES / REVENUE ANALYSIS---------

---------total revenue---

select sum(price) as total_revenue
from [dbo].[products]


---------Revenue per customer----

select c.name,sum(p.price*oi.quantity) as total_revenue 
from [dbo].[customer]c join [dbo].[orders]o on c.customer_id = o.customer_id
                       join [dbo].[order_items] oi on o.order_id = oi.order_id
                       join [dbo].[products]p on oi.product_id = p.product_id
where o.status = 'Delivered'
group by c.name 
order by total_revenue  desc;

--------------Revenue per product------------------
select p.product_name,sum(p.price*oi.quantity) as total_revenue 
from [dbo].[customer]c join [dbo].[orders]o on c.customer_id = o.customer_id
                       join [dbo].[order_items] oi on o.order_id = oi.order_id
                       join [dbo].[products]p on oi.product_id = p.product_id
where o.status = 'Delivered'
group by p.product_name 
order by total_revenue  desc;


-------------Daily or monthly sales trend----

SELECT 
    o.order_date,
    SUM(p.price * oi.quantity) AS daily_revenue
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY o.order_date
ORDER BY o.order_date;

------total no of oreders ---------
select count(*) as total_product
from [dbo].[orders];

-----dilivered vs cancelled order vs pending orders ---
select status,count(*) as Total_count
from [dbo].[orders]
group by status;

--------average value order----


SELECT 
    AVG(order_value) AS avg_order_value
FROM (
    SELECT 
        o.order_id,
        SUM(p.price * oi.quantity) AS order_value
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    WHERE o.status = 'Delivered'
    GROUP BY o.order_id
) AS order_totals;

-------top coustomers------

SELECT 
    c.name,
    SUM(p.price * oi.quantity) AS total_revenue,
    RANK() OVER (ORDER BY SUM(p.price * oi.quantity) DESC) AS rank_
FROM customer c
JOIN orders o ON c.customer = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY c.name;



--------Total of Revenue--

SELECT 
    o.order_date,
    SUM(p.price * oi.quantity) AS daily_revenue,
    SUM(SUM(p.price * oi.quantity)) OVER (ORDER BY o.order_date) AS running_total
FROM [dbo].[orders] o
JOIN [dbo].[order_items] oi 
    ON o.order_id = oi.order_id
JOIN [dbo].[products] p 
    ON oi.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY o.order_date
ORDER BY o.order_date;


-----------Top 3 Products per Category=-----------

SELECT *
FROM (
    SELECT 
        p.category,
        p.product_name,
        SUM(p.price * oi.quantity) AS revenue,
        RANK() OVER (
            PARTITION BY p.category 
            ORDER BY SUM(p.price * oi.quantity) DESC
        ) AS rank_
    FROM [dbo].[products] p
    JOIN [dbo].[order_items] oi 
        ON p.product_id = oi.product_id
    JOIN [dbo].[orders] o 
        ON oi.order_id = o.order_id
    WHERE o.status = 'Delivered'
    GROUP BY p.category, p.product_name
) AS ranked
WHERE rank_ <= 3;



------------Customers Who Never Ordered---------


SELECT c.name
FROM [dbo].[customer] c
LEFT JOIN [dbo].[orders] o 
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;